package com.alura.aluraeventos.config;

public class jsonParidades {
    
    
    public String jsonImportacao() {
        return "{\r\n"
        + "      \"paridades\": [\r\n"
        + "        {\r\n"
        + "          \"tabela\": \"BASF\",\r\n"
        + "          \"producoes\": [\r\n"
        + "            {\r\n"
        + "              \"producao\": \"BOURBON 2024\",\r\n"
        + "              \"produtos\": [\r\n"
        + "                {\r\n"
        + "                  \"descricao\": \"SOLUÇÃO BOURBON 1 | OPERA 4 X 5 | CANTUS 10 X 0.5 | HEAT®.10X0.35 KG.BR\",\r\n"
        + "                  \"valor\": 0.486,\r\n"
        + "                  \"composicao\": [\r\n"
        + "                    {\r\n"
        + "                      \"descricao\": \"OPERA 4 X 5\",\r\n"
        + "                      \"embalagem\": 5,\r\n"
        + "                      \"dose\": 3\r\n"
        + "                    },\r\n"
        + "                    {\r\n"
        + "                      \"descricao\": \"CANTUS 10 X 0.5\",\r\n"
        + "                      \"embalagem\": 0.5,\r\n"
        + "                      \"dose\": 0.15\r\n"
        + "                    },\r\n"
        + "                    {\r\n"
        + "                      \"descricao\": \"HEAT®.10X0.35 KG.BR\",\r\n"
        + "                      \"embalagem\": 0.35,\r\n"
        + "                      \"dose\": 0.035\r\n"
        + "                    }\r\n"
        + "                  ]\r\n"
        + "                },\r\n"
        + "                {\r\n"
        + "                  \"descricao\": \"SOLUÇÃO BOURBON 2 | OPERA 4 X 5 | ORKESTRA (TM) SC.10X1 L.BR | HEAT®.10X0.35 KG.BR\",\r\n"
        + "                  \"valor\": 0.524,\r\n"
        + "                  \"composicao\": [\r\n"
        + "                    {\r\n"
        + "                      \"descricao\": \"OPERA 4 X 5\",\r\n"
        + "                      \"embalagem\": 5,\r\n"
        + "                      \"dose\": 3\r\n"
        + "                    },\r\n"
        + "                    {\r\n"
        + "                      \"descricao\": \"ORKESTRA (TM) SC.10X1 L.BR\",\r\n"
        + "                      \"embalagem\": 1,\r\n"
        + "                      \"dose\": 0.3\r\n"
        + "                    },\r\n"
        + "                    {\r\n"
        + "                      \"descricao\": \"HEAT®.10X0.35 KG.BR\",\r\n"
        + "                      \"embalagem\": 0.35,\r\n"
        + "                      \"dose\": 0.035\r\n"
        + "                    }\r\n"
        + "                  ]\r\n"
        + "                },\r\n"
        + "                {\r\n"
        + "                  \"descricao\": \"TUTOR®.1X5 KG.BR\",\r\n"
        + "                  \"embalagem\": 5,\r\n"
        + "                  \"valor\": 0.101\r\n"
        + "                },\r\n"
        + "                {\r\n"
        + "                  \"descricao\": \"TUTOR ®.1X25\",\r\n"
        + "                  \"embalagem\": 25,\r\n"
        + "                  \"valor\": 0.0956\r\n"
        + "                },\r\n"
        + "                {\r\n"
        + "                  \"descricao\": \"COMET 4 X 5\",\r\n"
        + "                  \"embalagem\": 5,\r\n"
        + "                  \"valor\": 0.1759\r\n"
        + "                },\r\n"
        + "                {\r\n"
        + "                  \"descricao\": \"COMET 10 X 1\",\r\n"
        + "                  \"embalagem\": 1,\r\n"
        + "                  \"valor\": 0.1882\r\n"
        + "                },\r\n"
        + "                {\r\n"
        + "                  \"descricao\": \"ABACUS® HC.4X5 L.BR\",\r\n"
        + "                  \"embalagem\": 5,\r\n"
        + "                  \"valor\": 0.2886\r\n"
        + "                }\r\n"
        + "              ]\r\n"
        + "            }\r\n"
        + "            \r\n"
        + "          ],\r\n"
        + "          \"validade\": \"13/03/2023 - 12:00\"\r\n"
        + "        }\r\n"
        + "      ]\r\n"
        + "  }";
  }

}
